use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'AFPageClient_Example' do
  pod 'AFPageClient', :path => '../'
  pod 'MJRefresh'
  target 'AFPageClient_Tests' do
    inherit! :search_paths

    
  end
end
